spring:
  application:
    name: repository-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/package_systemDB
    username: postgres
    password: postgres

storage:
    strategy: object-storage
    fs:
        base-path: uploads
    obj:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket: repsy-packages